apiRules:
- exclude:
    uidRegex: ^System\.
    type: Namespace
- exclude:
    uidRegex: ^Microsoft\.
    type: Namespace
- exclude:
    uidRegex: \.Program$
    type: Type
- exclude:
    uidRegex: \.Startup$
    type: Type
- include:
    uidRegex: ^Jiro\.
    type: Namespace
- include:
    uidRegex: ^Jiro\.
    type: Type
