version: "3.7"
services:
  api:
    container_name: jiroapi
    build: 
      context: ./Jiro.Kernel
      dockerfile: Dockerfile
    ports: 
      - 5000:80 
      - 5001:443 
    environment:
      - CONFIG_PATH=/shared/appsettings.json
      - API_LOGS_PATH=/shared/logs/jiro.log
      - JIRO_DB_CONN=/shared/jiro.db
    volumes:
      - jiro_shared:/shared/

  tokenizer:
    container_name: jirotokenizer
    build: 
      context: ./Jiro.TokenApi
      dockerfile: Dockerfile
    ports: 
      - 8000:80 
    volumes:
      - jiro_shared:/shared/

volumes:
  jiro_shared:
