name: Docker Build & Security

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "Dockerfile"
      - "**/Dockerfile"
      - ".github/workflows/docker-build.yml"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "src/**"
      - "Dockerfile"
      - "**/Dockerfile"
      - ".github/workflows/docker-build.yml"

env:
  DOCKER_IMAGE_NAME: "jiro-kernel"
  REGISTRY: ghcr.io

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build & Verification

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare configuration files
        run: |
          if [ ! -f ./src/Jiro.Kernel/Jiro.App/appsettings.json ]; then
            cp ./src/Jiro.Kernel/Jiro.App/appsettings.example.json ./src/Jiro.Kernel/Jiro.App/appsettings.json
            echo "✅ Copied appsettings.example.json to appsettings.json"
          else
            echo "✅ appsettings.json already exists"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/Jiro.Kernel
          file: ./src/Jiro.Kernel/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Test Docker image
        run: |
          # Get the first tag for testing
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "Testing Docker image: $IMAGE_TAG"

          # Test 1: Basic startup validation in test mode
          echo "🧪 Running startup validation test..."
          if docker run --rm --name jiro-kernel-startup-test -e JIRO_TEST_MODE=true $IMAGE_TAG --test-mode; then
            echo "✅ Startup validation test passed"
          else
            echo "❌ Startup validation test failed"
            exit 1
          fi

          # Test 2: Container starts and basic health check
          echo "🏥 Running container health test..."
          if docker run -d --name jiro-kernel-health-test -e JIRO_TEST_MODE=true $IMAGE_TAG; then
            echo "✅ Container started successfully"
            sleep 5
            
            # Check if container is still running or exited gracefully
            if docker ps | grep -q jiro-kernel-health-test; then
              echo "✅ Container is running properly"
              docker stop jiro-kernel-health-test
              docker rm jiro-kernel-health-test
            else
              # Check exit code
              EXIT_CODE=$(docker inspect jiro-kernel-health-test --format='{{.State.ExitCode}}')
              if [ "$EXIT_CODE" = "0" ]; then
                echo "✅ Container exited gracefully (exit code 0)"
                docker rm jiro-kernel-health-test
              else
                echo "❌ Container stopped with exit code: $EXIT_CODE"
                echo "Container logs:"
                docker logs jiro-kernel-health-test || true
                docker rm jiro-kernel-health-test || true
                exit 1
              fi
            fi
          else
            echo "❌ Container failed to start"
            echo "Container logs:"
            docker logs jiro-kernel-health-test || true
            docker rm jiro-kernel-health-test || true
            exit 1
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: "sarif"
          output: "trivy-results.sarif"
        continue-on-error: true

      - name: Check Trivy results file
        id: check-trivy-results
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "trivy-file-exists=true" >> $GITHUB_OUTPUT
            echo "✅ Trivy results file created successfully"
            ls -la trivy-results.sarif
          else
            echo "trivy-file-exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ Trivy results file not found"
            echo "Files in current directory:"
            ls -la
          fi

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && steps.check-trivy-results.outputs.trivy-file-exists == 'true'
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ./src/Jiro.Kernel
          file: ./src/Jiro.Kernel/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker build completed
        run: |
          echo "✅ Docker build and security scanning completed"
          echo "📦 Built image: ${{ steps.meta.outputs.tags }}"
